name: api_integrations
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-408.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  json_serializable: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
